# Generated by Django 5.1.5 on 2025-07-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.FloatField(blank=True, null=True, verbose_name='Indice de masa corporal'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='talla',
            field=models.FloatField(blank=True, null=True, verbose_name='Indice de masa corporal'),
        ),
    ]
