# Generated by Django 5.1.5 on 2025-02-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_ecg_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='foto',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='imc',
            field=models.FloatField(blank=True, null=True, verbose_name='Indice de masa corporal'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono'),
        ),
    ]
